services:

  postgres:
    image: postgres:16
    container_name: incident_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incident_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d incident_db"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend
      dockerfile: DockerFile

    container_name: rootcause_backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - chroma_data:/app/chroma_db


volumes:
  postgres_data:
  chroma_data: