"""add advanced ai analysis fields

Revision ID: 2f9cdd129334
Revises: c6ca7b6a8a1d
Create Date: 2026-08-05 09:38:16.629992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9cdd129334'
down_revision: Union[str, Sequence[str], None] = 'c6ca7b6a8a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('executive_summary', sa.Text(), nullable=False))
    op.add_column('analysis', sa.Column('confidence', sa.Integer(), nullable=False))
    op.add_column('analysis', sa.Column('severity_prediction', sa.String(length=20), nullable=False))
    op.add_column('analysis', sa.Column('business_impact', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'business_impact')
    op.drop_column('analysis', 'severity_prediction')
    op.drop_column('analysis', 'confidence')
    op.drop_column('analysis', 'executive_summary')
    # ### end Alembic commands ###
