"""add created_by to incidents

Revision ID: 52ae193d9dd5
Revises: 26e908eb5f19
Create Date: 2026-07-22 19:13:52.583345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ae193d9dd5'
down_revision: Union[str, Sequence[str], None] = '26e908eb5f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'incidents', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'created_by')
    # ### end Alembic commands ###
