"""enhance ai analysis

Revision ID: 6ab52d3289ea
Revises: 2f9cdd129334
Create Date: 2026-08-05 10:16:02.573466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab52d3289ea'
down_revision: Union[str, Sequence[str], None] = '2f9cdd129334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('analysis', sa.Column('subcategory', sa.String(length=100), nullable=False))
    op.add_column('analysis', sa.Column('affected_component', sa.String(length=100), nullable=False))
    op.add_column('analysis', sa.Column('priority', sa.String(length=10), nullable=False))
    op.drop_column('analysis', 'severity_prediction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('severity_prediction', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('analysis', 'priority')
    op.drop_column('analysis', 'affected_component')
    op.drop_column('analysis', 'subcategory')
    op.drop_column('analysis', 'category')
    # ### end Alembic commands ###
