"""cascade delete

Revision ID: 8ee419de7119
Revises: 1df1d1a170bd
Create Date: 2026-07-12 22:53:01.293964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee419de7119'
down_revision: Union[str, Sequence[str], None] = '1df1d1a170bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analysis_incident_id_fkey'), 'analysis', type_='foreignkey')
    op.create_foreign_key(None, 'analysis', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('logs_incident_id_fkey'), 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(op.f('logs_incident_id_fkey'), 'logs', 'incidents', ['incident_id'], ['id'])
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_incident_id_fkey'), 'analysis', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###
