"""incident response report

Revision ID: b6a210cfb9f8
Revises: 6ab52d3289ea
Create Date: 2026-08-05 10:39:59.936510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a210cfb9f8'
down_revision: Union[str, Sequence[str], None] = '6ab52d3289ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('confidence_reason', sa.Text(), nullable=False))
    op.add_column('analysis', sa.Column('immediate_actions', sa.Text(), nullable=False))
    op.add_column('analysis', sa.Column('runbook', sa.Text(), nullable=False))
    op.add_column('analysis', sa.Column('risk_if_ignored', sa.Text(), nullable=False))
    op.add_column('analysis', sa.Column('prevention', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'prevention')
    op.drop_column('analysis', 'risk_if_ignored')
    op.drop_column('analysis', 'runbook')
    op.drop_column('analysis', 'immediate_actions')
    op.drop_column('analysis', 'confidence_reason')
    # ### end Alembic commands ###
