# Incident Actions
INCIDENT_CREATED = "INCIDENT_CREATED"
STATUS_CHANGED = "STATUS_CHANGED"
SEVERITY_CHANGED = "SEVERITY_CHANGED"
ENGINEER_ASSIGNED = "ENGINEER_ASSIGNED"

# Default Pagination
DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100